//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme1.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizikselOzellikler
    {
        public double Guc { get; set; }
        public Nullable<double> Hız { get; set; }
        public Nullable<double> Ceviklik { get; set; }
        public Nullable<double> Dayanıklılık { get; set; }
        public Nullable<double> Zıplama { get; set; }
        public Nullable<double> Denge { get; set; }
        public Nullable<int> SporcuId { get; set; }
    
        public virtual Sporcu Sporcu { get; set; }
    }
}
