//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme1.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaktikselOzellikler
    {
        public double Pas { get; set; }
        public double Shoot { get; set; }
        public double Bitiricilik { get; set; }
        public double Markaj { get; set; }
        public double DuranTop { get; set; }
        public int SporcuId { get; set; }
    
        public virtual Sporcu Sporcu { get; set; }
    }
}
